# Generated by Django 5.0.4 on 2024-05-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_groupnprojectassoc_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupnprojectassoc',
            name='project',
        ),
        migrations.AddField(
            model_name='groupnprojectassoc',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='api.project'),
        ),
    ]
