# Generated by Django 5.0.4 on 2024-05-08 02:47

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_groupnprojectassoc_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='group',
        ),
        migrations.AlterField(
            model_name='groupnprojectassoc',
            name='project',
            field=models.ManyToManyField(to='api.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(default=api.models.Group.get_default_group_id, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.group'),
        ),
    ]
