# Generated by Django 5.0.4 on 2024-05-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_task_group_alter_groupnprojectassoc_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnprojectassoc',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='api.project'),
        ),
    ]
