# Generated by Django 5.0.4 on 2024-05-09 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_task_project_name_task_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnprojectassoc',
            name='project',
            field=models.ManyToManyField(to='api.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='task',
            name='project_name',
        ),
        migrations.AddField(
            model_name='task',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.project'),
        ),
    ]
