# Generated by Django 5.0.4 on 2024-06-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_task_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ManyToManyField(to='api.group'),
        ),
    ]
